### ISSUE TITLE
ImportError: cannot import name 'DeformUnfold'

### ISSUE THREAD

**Issue by songlin** [Willy0919/DDMP-3D#3]
Hi, 
I installed `maskrcnn-benchmark` by following the installation step [here](https://github.com/lzrobots/dgmn/blob/master/INSTALL.md).

but when i try to run 
```
sh train.sh
```
I got error:
```
Traceback (most recent call last):
  File "scripts/train.py", line 213, in <module>
    main(sys.argv[1:])
  File "scripts/train.py", line 87, in main
    rpn_net, optimizer, scheduler = init_training_model(conf, paths.output, conf_name)
  File "/home/songlin/Projects/DDMP-3D/lib/core.py", line 66, in init_training_model
    network = absolute_import(dst_path)
  File "/home/songlin/Projects/DDMP-3D/lib/util.py", line 98, in absolute_import
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/songlin/Projects/DDMP-3D/output/depth_ddmp/Adaptive_block2_resnet_depth50_ddmp/resnet_ddmp.py", line 7, in <module>
    from maskrcnn_benchmark.layers import DeformUnfold
ImportError: cannot import name 'DeformUnfold'
```

I searched the keyword ` DeformUnfold` in the original `maskrcnn_benchmark` [project](https://github.com/facebookresearch/maskrcnn-benchmark), but found nothing.

Please help.
Thank you

**Comment by Willy0919** [comment]
@songlin You need to install the modified version of maskrcnn_benchmark in https://github.com/lzrobots/dgmn, which contains the function in maskrcnn_benchmark.layers.

**Comment by songlin** [comment]
@Willy0919 Thank you for the quick reply. Problem solved.
